FROM --platform=linux/amd64 node:16-alpine3.17 AS builder

RUN apk add --no-cache libc6-compat openssl1.1-compat
WORKDIR /app

COPY . .
RUN yarn install
RUN yarn build server

FROM node:16-alpine3.17

WORKDIR /app
COPY --from=builder ./app/dist/apps/server .

CMD [ "node", "main.js" ]
