FROM node:alpine AS builder

WORKDIR /app
COPY . .
RUN yarn install --production
RUN ls -a
RUN yarn build server

FROM node:alpine

WORKDIR /app
COPY --from=builder /app/dist/apps/server ./

CMD [ "node", "main.js" ]
