export const ownerDiscoveryTerms = [
  'location:iran type:org',
  'location:iran type:user',
  'location:tehran type:org',
  'location:tehran type:user',
  // ^ These are split into two different terms because github has a limitation of maximum 1k items and users with the location `iran` are - at the moment of writing this - almost 20k. this helps us get more users.
  'location:ایران',
  'location:alborz',
  'location:karaj',
  'location:mashhad',
  'location:isfahan',
  'location:esfehan',
  'location:tabriz',
  'location:shiraz',
  'location:fars',
  'location:qom',
  'location:ahvaz',
  'location:ahwaz',
  'location:rasht',
  'location:kermanshah',
  'location:hamedan',
  'location:yazd',
  'iranian',
];
