export const ownerDiscoveryTerms = [
  'location:iran type:org',
  'location:iran type:user',
  'location:tehran type:org',
  'location:tehran type:user',
  // ^ These are split into two different terms because github has a limitation of maximum 1k items and users with the location `iran` are - at the moment of writing this - almost 20k. this helps us get more users.
  'location:ایران',
  'location:alborz',
  'location:karaj',
  'location:mashhad',
  'location:isfahan',
  'location:esfehan',
  'location:tabriz',
  'location:shiraz',
  'location:fars',
  'location:qom',
  'location:ahvaz',
  'location:ahwaz',
  'location:rasht',
  'location:kermanshah',
  'location:hamedan',
  'location:yazd',
  'iranian',

  /*
    Persian names

    Please avoid adding just *any* Iranian names. 

    Some examples to avoid:
    - Mohammad: It's an Arabic name, will lead us to Arab users
    - Armin: It's a German name too, will lead us to German users
    - Arya/Aryan/Arshiya/Benyamin: Will lead us to Indian users
    - Dana: It's a short name so it could be inside other words, leading us to dirty data

    Some good examples:
    - Alireza, Afrasiab: They probably can't be inside other words, since they're long enough. Also they are only used in Iran.


    Please do test the names on `https://api.github.com/search/users?q=NAME&sort=followers` before adding them
  */

  // Combined names
  'Amirali',
  'Amirhosein',
  'Amirhossein',
  'Amirmohamad',
  'Amirmohammad',
  'Amirreza',
  'Abdolreza',
  'Ahmadreza',
  'Alireza',
  'Gholamreza',
  'Hamidreza',
  'Mahmoodreza',
  'Mohammadreza',
  'Mohammadali',
  'Mohammadamin',
  'Mohammadbagher',
  'Mohammadebrahim',
  'Mohammaderfan',
  'Mohammadhadi',
  'Mohammadhassan',
  'Mohammadhossein',
  'Mohammadjafar',
  'Mohammadjavad',
  'Mohammadkazem',
  'Mohammadmahdi',
  'Mohammadmehdi',
  'Mohammadrasoul',
  'Mohammadreza',
  'Mohammadsadegh',
  'Mohammadtaghi',
  'Mohamadali',
  'Mohamadamin',
  'Mohamadbagher',
  'Mohamadebrahim',
  'Mohamaderfan',
  'Mohamadhadi',
  'Mohamadhassan',
  'Mohamadhossein',
  'Mohamadjafar',
  'Mohamadjavad',
  'Mohamadkazem',
  'Mohamadmahdi',
  'Mohamadmehdi',
  'Mohamadrasoul',
  'Mohamadreza',
  'Mohamadsadegh',
  'Mohamadtaghi',

  // The following names might include dirty data and are commented out for now.

  // // Male
  // 'Afrasiab',
  // 'Anoushirevan',
  // 'Ardeshir',
  // 'Dariush',
  // 'Farrokh',
  // 'Farshid',
  // 'Feraydoon',
  // 'Fereydoon',
  // 'Farshad',
  // 'Homayun',
  // 'Homayoon',
  // 'Houshang',
  // 'Khashayar',
  // 'Kiarash',
  // 'Kourosh',
  // 'Manuchehr',
  // 'Mehrdad',
  // 'Mehrzad',
  // 'Pezhman',
  // 'Sepanta',
  // 'Shahryar',
  // 'Shervin',
  // 'Soroush',

  // // Female
  // 'Anousheh',
  // 'Farzaneh',
  // 'Fereshteh',
  // 'Gordafarid',
  // 'Mahshid',
  // 'Mozhgan',
  // 'Manizheh',
  // 'Niousha',
  // 'Niloufar',
  // 'Nazanin',
  // 'Nooshin',
  // 'Parastu',
  // 'Parastoo',
  // 'Parmida',
  // 'Sepideh',
  // 'Shaghayegh',
  // 'Shireen',
  // 'Tahmineh',

  // // Surname
  // 'Darvishi',
  // 'Dehdari',
  // 'Dehkordi',
  // 'Esfahani',
  // 'Esfandiari',
  // 'Farrokhzad',
  // 'Farahmand',
  // 'Ghorbani',
  // 'Ghamsari',
  // 'Ghassemi',
  // 'Hanifnejad',
  // 'Hedayati',
  // 'Homayoun',
  // 'Hooshang',
  // 'Hooshmand',
  // 'Jahandar',
  // 'Jahangir',
  // 'Jamshidi',
  // 'Kordbacheh',
  // 'Kermanshahchi',
  // 'Keshavarz',
  // 'Khorasani',
  // 'Mousavian',
  // 'Mazandarani',
  // 'Mehregan',
  // 'Mobasseri',
  // 'Piranshahri',
  // 'Rostami',
  // 'Salehrad',
  // 'Shir-Del',
  // 'Shirazi',
  // 'Soltani',
  // 'Tehrani',
  // 'Teymouri',
];
