export enum OwnerReason {
  PERSIAN_REPOSITORY = 'PERSIAN_REPOSITORY',
  SUBMISSION = 'SUBMISSION',
  GITHUB_LOCATION = 'GITHUB_LOCATION',
  GITHUB_ORG_LOCATION = 'GITHUB_ORG_LOCATION',
  ORGANIZATION_PRESENCE = 'ORGANIZATION_PRESENCE',
}
