name: Web-Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: update-liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          npm i -g @liara/cli@3
          SSR_GRAPHQL_ENDPOINT=https://api.matnbaz.net/graphql liara deploy --app="matnbaz-web-prod" --port=3000 --platform="docker" --dockerfile="apps/web/Dockerfile" --api-token="$LIARA_TOKEN" --detach
